/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request, Response } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FileInterceptor } from "@nestjs/platform-express";
import { JadeService } from "../jade.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JadeCreateInput } from "./JadeCreateInput";
import { Jade } from "./Jade";
import { JadeFindManyArgs } from "./JadeFindManyArgs";
import { JadeWhereUniqueInput } from "./JadeWhereUniqueInput";
import { JadeUpdateInput } from "./JadeUpdateInput";
import { AuctionFindManyArgs } from "../../auction/base/AuctionFindManyArgs";
import { Auction } from "../../auction/base/Auction";
import { AuctionWhereUniqueInput } from "../../auction/base/AuctionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class JadeControllerBase {
  constructor(
    protected readonly service: JadeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Jade })
  @nestAccessControl.UseRoles({
    resource: "Jade",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createJade(@common.Body() data: JadeCreateInput): Promise<Jade> {
    return await this.service.createJade({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        image: true,
        startingBid: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Jade] })
  @ApiNestedQuery(JadeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Jade",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jades(@common.Req() request: Request): Promise<Jade[]> {
    const args = plainToClass(JadeFindManyArgs, request.query);
    return this.service.jades({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        image: true,
        startingBid: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Jade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Jade",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jade(
    @common.Param() params: JadeWhereUniqueInput
  ): Promise<Jade | null> {
    const result = await this.service.jade({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        image: true,
        startingBid: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Jade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Jade",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateJade(
    @common.Param() params: JadeWhereUniqueInput,
    @common.Body() data: JadeUpdateInput
  ): Promise<Jade | null> {
    try {
      return await this.service.updateJade({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          image: true,
          startingBid: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Jade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Jade",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteJade(
    @common.Param() params: JadeWhereUniqueInput
  ): Promise<Jade | null> {
    try {
      return await this.service.deleteJade({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          image: true,
          startingBid: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Put(":id/image")
  @common.UseInterceptors(FileInterceptor("file"))
  @swagger.ApiConsumes("multipart/form-data")
  @swagger.ApiBody({
    schema: {
      type: "object",

      properties: {
        file: {
          type: "string",
          format: "binary",
        },
      },
    },
  })
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiCreatedResponse({
    type: Jade,
    status: "2XX",
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async uploadImage(
    @common.Param()
    params: JadeWhereUniqueInput,
    @common.UploadedFile()
    file: Express.Multer.File
  ): Promise<Jade> {
    return this.service.uploadImage(
      {
        where: params,
      },
      Object.assign(file, {
        filename: file.originalname,
      })
    );
  }

  @common.Get(":id/image")
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiOkResponse({
    type: common.StreamableFile,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async downloadImage(
    @common.Param()
    params: JadeWhereUniqueInput,
    @common.Res({
      passthrough: true,
    })
    res: Response
  ): Promise<common.StreamableFile> {
    const result = await this.service.downloadImage({
      where: params,
    });

    if (result === null) {
      throw new errors.NotFoundException(
        "No resource was found for ",
        JSON.stringify(params)
      );
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${result.filename}`
    );
    res.setHeader("Content-Type", result.mimetype);
    return result.stream;
  }

  @common.Delete(":id/image")
  @swagger.ApiOkResponse({
    type: Jade,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async deleteImage(
    @common.Param()
    params: JadeWhereUniqueInput
  ): Promise<Jade> {
    return this.service.deleteImage({
      where: params,
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/auctions")
  @ApiNestedQuery(AuctionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Auction",
    action: "read",
    possession: "any",
  })
  async findAuctions(
    @common.Req() request: Request,
    @common.Param() params: JadeWhereUniqueInput
  ): Promise<Auction[]> {
    const query = plainToClass(AuctionFindManyArgs, request.query);
    const results = await this.service.findAuctions(params.id, {
      ...query,
      select: {
        createdAt: true,
        endingTime: true,
        highestBid: true,
        id: true,

        jade: {
          select: {
            id: true,
          },
        },

        startingPrice: true,
        startingTime: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/auctions")
  @nestAccessControl.UseRoles({
    resource: "Jade",
    action: "update",
    possession: "any",
  })
  async connectAuctions(
    @common.Param() params: JadeWhereUniqueInput,
    @common.Body() body: AuctionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auctions: {
        connect: body,
      },
    };
    await this.service.updateJade({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/auctions")
  @nestAccessControl.UseRoles({
    resource: "Jade",
    action: "update",
    possession: "any",
  })
  async updateAuctions(
    @common.Param() params: JadeWhereUniqueInput,
    @common.Body() body: AuctionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auctions: {
        set: body,
      },
    };
    await this.service.updateJade({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/auctions")
  @nestAccessControl.UseRoles({
    resource: "Jade",
    action: "update",
    possession: "any",
  })
  async disconnectAuctions(
    @common.Param() params: JadeWhereUniqueInput,
    @common.Body() body: AuctionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auctions: {
        disconnect: body,
      },
    };
    await this.service.updateJade({
      where: params,
      data,
      select: { id: true },
    });
  }
}
